### ISSUE TITLE
Cannot install from homebrew

### ISSUE THREAD

**Issue by halostatue** [joshuaclayton/unused#97]
I’ve installed `cabal-install` 2.2.0.0 and after tapping and installing, I get the following output:

```
==> Installing unused from joshuaclayton/formulae
==> Downloading https://github.com/joshuaclayton/unused/archive/v0.8.0.0.tar.gz
Already downloaded: /Users/austin/Library/Caches/Homebrew/unused--0.8.0.0.tar.gz
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=4 --max-backjumps=100000 --only-dependencies
Last 15 lines from /Users/austin/Library/Logs/Homebrew/unused/03.cabal:
base>=4.5 && <4.11)
[__4] rejecting: base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0,
base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: primitive, vector, base, unused,
cassava
Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

Error: 784: unexpected token at '{"json_class":"ErrorDuringExecution","m":"Failure while executing; `/usr/bin/sandbox-exec -f /private/tmp/homebrew20180817-38322-1oghpvn.sb nice /Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby -W0 -I /Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0:/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0:/Users/austin/.brew/Library/Homebrew/cask/lib:/Users/austin/.brew/Library/Homebrew -- /Users/austin/.brew/Library/Homebrew/build.rb /Users/austin/.brew/Library/Taps/joshuaclayton/homebrew-formulae/Formula/unused.rb` exited with 1.","b":["/Users/austin/.brew/Library/Homebrew/utils.rb:301:in `safe_system'","/Users/austin/.brew/Library/Homebrew/sandbox.rb:96:in `exec'","/Users/austin/.brew/Library/Homebrew/formula_installer.rb:754:in `block in build'","/Users/austin/.brew/Library/Homebrew/utils/fork.rb:18:in `block (3 levels) in safe_fork'","/Users/austin/.brew/Library/Homebrew/utils/fork.rb:12:in `fork'","/Users/austin/.brew/Library/Homebrew/utils/fork.rb:12:in `block (2 levels) in safe_fork'","/Users/austin/.brew/Library/Homebrew/utils/fork.rb:9:in `open'","/Users/austin/.brew/Library/Homebrew/utils/fork.rb:9:in `block in safe_fork'","/Users/austin/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'","/Users/austin/.brew/Library/Homebrew/utils/fork.rb:8:in `safe_fork'","/Users/austin/.brew/Library/Homebrew/formula_installer.rb:738:in `build'","/Users/austin/.brew/Library/Homebrew/formula_installer.rb:331:in `install'","/Users/austin/.brew/Library/Homebrew/cmd/install.rb:321:in `install_formula'","/Users/austin/.brew/Library/Homebrew/cmd/install.rb:253:in `block in install'","/Users/austin/.brew/Library/Homebrew/cmd/install.rb:251:in `each'","/Users/austin/.brew/Library/Homebrew/cmd/install.rb:251:in `install'","/Users/austin/.brew/Library/Homebrew/brew.rb:87:in `<main>'"]}'
```

Ideas? (I also have a failure with installing from stack, but will report that separately, although they may be related.)

**Comment by joshuaclayton** [comment]
@halostatue apologies on the delay here; I've pushed up a [new version of unused](https://github.com/joshuaclayton/unused/releases/tag/v0.9.0.0) which updates external package dependencies and [updated the Homebrew formula as well](https://github.com/joshuaclayton/homebrew-formulae/commit/ebac0787c90f8ac558b6b0d7d92802eed2ba7306).

With this, you should be able to run `brew update && brew upgrade joshuaclayton/formulae/unused` (assuming a successful previous tapped formula) and be good to go.
